import os

class Config:
    DATABASE_URL = os.getenv("DATABASE_URL")
    CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
    AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
    AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")
    CHROMA_DB_PATH = os.getenv("CHROMA_DB_PATH")
    UPLOAD_FOLDER = os.getenv("UPLOAD_FOLDER")
    MAX_FILE_SIZE = os.getenv("MAX_FILE_SIZE")
    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
    JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
    JWT_EXPIRE_MINUTES = os.getenv("JWT_EXPIRE_MINUTES")
    DEFAULT_ADMIN_USERNAME = os.getenv("DEFAULT_ADMIN_USERNAME")
    DEFAULT_ADMIN_PASSWORD = os.getenv("DEFAULT_ADMIN_PASSWORD")
    DEFAULT_ANALYST_USERNAME = os.getenv("DEFAULT_ANALYST_USERNAME")
    DEFAULT_ANALYST_PASSWORD = os.getenv("DEFAULT_ANALYST_PASSWORD")

config = Config()
